name: Node CI

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - 'package.json'
      - '.github/workflows/node.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Lint and Build
        run: |
          npm run lint || true
          npm run build || true

