name: Validate Data Logs

on:
  push:
    paths:
      - 'data/logger/*.json'
      - '.github/workflows/validate-logs.yml'
  pull_request:
    paths:
      - 'data/logger/*.json'
      - '.github/workflows/validate-logs.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run log validation
        run: python data/logger/validate_log.py
